"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const postRoutes_1 = __importDefault(require("./postRoutes"));
const userRoutes_1 = __importDefault(require("./userRoutes"));
const neighborhoodRoutes_1 = __importDefault(require("./neighborhoodRoutes"));
const buildingRoutes_1 = __importDefault(require("./buildingRoutes"));
const commentRoutes_1 = __importDefault(require("./commentRoutes"));
const chatMessageRoutes_1 = __importDefault(require("./chatMessageRoutes"));
const router = express.Router();
router.use("/posts", postRoutes_1.default);
router.use("/users", userRoutes_1.default);
router.use("/neighborhoods", neighborhoodRoutes_1.default);
router.use("/buildings", buildingRoutes_1.default);
router.use("/comments", commentRoutes_1.default);
router.use("/chatMessages", chatMessageRoutes_1.default);
exports.default = router;
